// Power Query M: import and prepare AI_LSI_Demo_Historical_Data - Copy.csv
// Paste into Power BI Desktop: Home -> Get Data -> Blank Query -> Advanced Editor
let
    Source = Csv.Document(File.Contents("C:\\Users\\UM_AS\\OneDrive\\Documents.worktrees\\pbix-dashboard-learner-guide-integration\\AI_LSI_Demo_Historical_Data - Copy.csv"), [Delimiter=",", Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    // Normalize column names (trim spaces)
    Trimmed = Table.TransformColumnNames(PromotedHeaders, Text.Trim),
    // Rename known columns to consistent names (adjust if your CSV differs)
    Renamed = Table.RenameColumns(Trimmed, {
        {"Date","Date"},
        {"Temperature (C)","Temperature_C"},
        {"Flow (m3/h)","Flow_m3_h"},
        {"Calcium (mg/L)","Calcium_mg_L"},
        {"Alkalinity (mg/L)","Alkalinity_mg_L"},
        {"TDS (mg/L)","TDS_mg_L"},
        {"LSI","LSI"}
    }, MissingField.Ignore),
    // Change data types
    Typed = Table.TransformColumnTypes(Renamed,{
        {"Date", type datetime},
        {"Temperature_C", type number},
        {"Flow_m3_h", type number},
        {"pH", type number},
        {"Calcium_mg_L", type number},
        {"Alkalinity_mg_L", type number},
        {"TDS_mg_L", type number},
        {"LSI", type number}
    }),
    // Create a DateOnly column if you prefer
    DateOnly = Table.AddColumn(Typed, "DateOnly", each Date.From([Date]), type date)
in
    DateOnly

// If the CSV path changes, update File.Contents path or use Home->Get Data to select file and then paste the transforms only.